import { EXIT_CODE } from "./constants"

export type ErrorCode =
  | "NOT_GIT_REPOSITORY"
  | "INVALID_ARGUMENT"
  | "UNKNOWN_COMMAND"
  | "UNSAFE_FLAG_REQUIRED"
  | "NOT_INITIALIZED"
  | "WORKTREE_NOT_FOUND"
  | "BRANCH_ALREADY_ATTACHED"
  | "BRANCH_ALREADY_EXISTS"
  | "BRANCH_IN_USE"
  | "TARGET_PATH_NOT_EMPTY"
  | "PATH_OUTSIDE_REPO"
  | "ABSOLUTE_PATH_NOT_ALLOWED"
  | "LOCK_CONFLICT"
  | "DETACHED_HEAD"
  | "DIRTY_WORKTREE"
  | "UNMERGED_WORKTREE"
  | "UNPUSHED_WORKTREE"
  | "LOCKED_WORKTREE"
  | "STASH_APPLY_FAILED"
  | "REMOTE_NOT_FOUND"
  | "REMOTE_BRANCH_NOT_FOUND"
  | "INVALID_REMOTE_BRANCH_FORMAT"
  | "HOOK_NOT_FOUND"
  | "DEPENDENCY_MISSING"
  | "REPO_LOCK_TIMEOUT"
  | "REPO_LOCK_STALE_RECOVERY_FAILED"
  | "HOOK_NOT_EXECUTABLE"
  | "HOOK_TIMEOUT"
  | "HOOK_FAILED"
  | "GIT_COMMAND_FAILED"
  | "INTERNAL_ERROR"

const ERROR_CODE_TO_EXIT_CODE: Record<ErrorCode, number> = {
  NOT_GIT_REPOSITORY: EXIT_CODE.NOT_GIT_REPOSITORY,
  INVALID_ARGUMENT: EXIT_CODE.INVALID_ARGUMENT,
  UNKNOWN_COMMAND: EXIT_CODE.INVALID_ARGUMENT,
  UNSAFE_FLAG_REQUIRED: EXIT_CODE.SAFETY_REJECTED,
  NOT_INITIALIZED: EXIT_CODE.SAFETY_REJECTED,
  WORKTREE_NOT_FOUND: EXIT_CODE.SAFETY_REJECTED,
  BRANCH_ALREADY_ATTACHED: EXIT_CODE.SAFETY_REJECTED,
  BRANCH_ALREADY_EXISTS: EXIT_CODE.SAFETY_REJECTED,
  BRANCH_IN_USE: EXIT_CODE.SAFETY_REJECTED,
  TARGET_PATH_NOT_EMPTY: EXIT_CODE.SAFETY_REJECTED,
  PATH_OUTSIDE_REPO: EXIT_CODE.SAFETY_REJECTED,
  ABSOLUTE_PATH_NOT_ALLOWED: EXIT_CODE.SAFETY_REJECTED,
  LOCK_CONFLICT: EXIT_CODE.SAFETY_REJECTED,
  DETACHED_HEAD: EXIT_CODE.SAFETY_REJECTED,
  DIRTY_WORKTREE: EXIT_CODE.SAFETY_REJECTED,
  UNMERGED_WORKTREE: EXIT_CODE.SAFETY_REJECTED,
  UNPUSHED_WORKTREE: EXIT_CODE.SAFETY_REJECTED,
  LOCKED_WORKTREE: EXIT_CODE.SAFETY_REJECTED,
  STASH_APPLY_FAILED: EXIT_CODE.SAFETY_REJECTED,
  REMOTE_NOT_FOUND: EXIT_CODE.SAFETY_REJECTED,
  REMOTE_BRANCH_NOT_FOUND: EXIT_CODE.SAFETY_REJECTED,
  INVALID_REMOTE_BRANCH_FORMAT: EXIT_CODE.INVALID_ARGUMENT,
  HOOK_NOT_FOUND: EXIT_CODE.SAFETY_REJECTED,
  DEPENDENCY_MISSING: EXIT_CODE.DEPENDENCY_MISSING,
  REPO_LOCK_TIMEOUT: EXIT_CODE.LOCK_FAILED,
  REPO_LOCK_STALE_RECOVERY_FAILED: EXIT_CODE.LOCK_FAILED,
  HOOK_NOT_EXECUTABLE: EXIT_CODE.HOOK_FAILED,
  HOOK_TIMEOUT: EXIT_CODE.HOOK_FAILED,
  HOOK_FAILED: EXIT_CODE.HOOK_FAILED,
  GIT_COMMAND_FAILED: EXIT_CODE.GIT_COMMAND_FAILED,
  INTERNAL_ERROR: EXIT_CODE.INTERNAL_ERROR,
}

export type CliErrorOptions = {
  readonly message: string
  readonly details?: Record<string, unknown>
  readonly cause?: unknown
}

export class CliError extends Error {
  readonly code: ErrorCode
  readonly exitCode: number
  readonly details: Record<string, unknown>

  constructor(code: ErrorCode, options: CliErrorOptions) {
    super(options.message, { cause: options.cause })
    this.code = code
    this.exitCode = ERROR_CODE_TO_EXIT_CODE[code]
    this.details = options.details ?? {}
  }
}

export const createCliError = (code: ErrorCode, options: CliErrorOptions): CliError => {
  return new CliError(code, options)
}

export const ensureCliError = (error: unknown): CliError => {
  if (error instanceof CliError) {
    return error
  }

  if (error instanceof Error) {
    return createCliError("INTERNAL_ERROR", { message: error.message, cause: error })
  }

  return createCliError("INTERNAL_ERROR", {
    message: "An unexpected error occurred",
    details: { value: String(error) },
  })
}
